# Generated by Django 6.0.3 on 2026-03-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='emUso',
            field=models.BooleanField(default=False),
        ),
    ]
